version: '3'

services:

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node ./login.js
    networks:
      - mysql-network
    volumes:
      - ./node:/usr/src/app
      #- exclude:/usr/src/app/node_modules/
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
    exclude: